# Header
# menu:
#   Home: /
#   Archives: /archives
#   Tags: /tags
#   Categories: /categories

# Title on top left of menu. Leave empty to use main blog title
menu_title: Accueil

# URL of the Home page image
index_cover: /images/home-bg.jpg

# Default post title
default_post_title: Sans Titre

# Comments. Choose one by filling up the information
comments:
  disqus_shortname:
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url:
gitlab_url:
linkedin_url:
mailto:
